AkademiaV2/Models/ColaboradoresTalleres.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AkademiaV2.Models
{
    public class ColaboradoresTalleres
    {
        public int Id { get; set; }
        public Colaboradores Colaboradores { get; set; }
        public int TalleresId { get; set; }
        public Talleres Taller { get; set; }
    }
}

AkademiaV2/Controllers/ColaboradoresTalleresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AkademiaV2.Data;
using AkademiaV2.Models;
using AkademiaV2.Services;
using Microsoft.AspNetCore.Authorization;
using AkademiaV2.Models.ViewModels;

namespace AkademiaV2.Controllers
{
    public class ColaboradoresTalleresController : Controller
    {
        private readonly IColaboradores _colaboradoresServices;
        private readonly ITalleres _talleresServices;
        private readonly IColaboradoresTalleres _colaboradoresTalleresServices;

        public ColaboradoresTalleresController(IColaboradores colaboradoresServices, ITalleres talleresServices, IColaboradoresTalleres colaboradoresTalleresServices)
        {

            _talleresServices = talleresServices;
            _colaboradoresTalleresServices = colaboradoresTalleresServices;
            _colaboradoresServices = colaboradoresServices;

        }

        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> ShowTaller_Colaboradores(int? id)
        {

            Colab_Taller_AsistentesVM colab_Taller_AsistentesVM = new Colab_Taller_AsistentesVM
            {
                Taller = await _talleresServices.GetTallerByIdAsync(id),
                Escoger_Facilitadores = await _colaboradoresServices.GetFacilitadoresAsync(),
            };
            return View(colab_Taller_AsistentesVM);
        }

        //Creo registros con el mismo id taller y varios id Facilitadores a ese mismo taller.Se crean x id_colaboradorestaller
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> CreateTaller_Colaboradores(Colab_Taller_AsistentesVM colab_Taller_AsistentesVM, int[] facilitadores_id)
        {
            int Tallerid = colab_Taller_AsistentesVM.TallerId;

            foreach (int i in facilitadores_id)
            {

                ColaboradoresTalleres colaboradoresTalleres = new ColaboradoresTalleres
                {
                    Colaboradores = await _colaboradoresServices.GetColaboradorByIdAsync(i),
                    Taller = await _talleresServices.GetTallerByIdAsync(Tallerid),

                };

                if (ModelState.IsValid)
                {
                    await _colaboradoresTalleresServices.CreateColaboradoresTalleres(colaboradoresTalleres);

                }
            }

            return RedirectToAction("ListaTalleres", "Talleres");
        }


        //// GET: ColaboradoresTalleres
        //public async Task<IActionResult> Index()
        //{
        //    var akademiaSystem = _context.ColaboradoresTalleres.Include(c => c.Taller);
        //    return View(await akademiaSystem.ToListAsync());
        //}

        //// GET: ColaboradoresTalleres/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var colaboradoresTalleres = await _context.ColaboradoresTalleres
        //        .Include(c => c.Taller)
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (colaboradoresTalleres == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(colaboradoresTalleres);
        //}

        //// GET: ColaboradoresTalleres/Create
        //public IActionResult Create()
        //{
        //    ViewData["TalleresId"] = new SelectList(_context.Talleres, "Id", "Descripcion");
        //    return View();
        //}

        //// POST: ColaboradoresTalleres/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,TalleresId")] ColaboradoresTalleres colaboradoresTalleres)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(colaboradoresTalleres);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["TalleresId"] = new SelectList(_context.Talleres, "Id", "Descripcion", colaboradoresTalleres.TalleresId);
        //    return View(colaboradoresTalleres);
        //}

        //// GET: ColaboradoresTalleres/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var colaboradoresTalleres = await _context.ColaboradoresTalleres.FindAsync(id);
        //    if (colaboradoresTalleres == null)
        //    {
        //        return NotFound();
        //    }
        //    ViewData["TalleresId"] = new SelectList(_context.Talleres, "Id", "Descripcion", colaboradoresTalleres.TalleresId);
        //    return View(colaboradoresTalleres);
        //}

        //// POST: ColaboradoresTalleres/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,TalleresId")] ColaboradoresTalleres colaboradoresTalleres)
        //{
        //    if (id != colaboradoresTalleres.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(colaboradoresTalleres);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!ColaboradoresTalleresExists(colaboradoresTalleres.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["TalleresId"] = new SelectList(_context.Talleres, "Id", "Descripcion", colaboradoresTalleres.TalleresId);
        //    return View(colaboradoresTalleres);
        //}

        //// GET: ColaboradoresTalleres/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var colaboradoresTalleres = await _context.ColaboradoresTalleres
        //        .Include(c => c.Taller)
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (colaboradoresTalleres == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(colaboradoresTalleres);
        //}

        //// POST: ColaboradoresTalleres/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var colaboradoresTalleres = await _context.ColaboradoresTalleres.FindAsync(id);
        //    _context.ColaboradoresTalleres.Remove(colaboradoresTalleres);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool ColaboradoresTalleresExists(int id)
        //{
        //    return _context.ColaboradoresTalleres.Any(e => e.Id == id);
        //}
    }
}

AkademiaV2/Views/ColaboradoresTalleres/Create.cshtml
@model AkademiaV2.Models.ColaboradoresTalleres

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ColaboradoresTalleres</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TalleresId" class="control-label"></label>
                <select asp-for="TalleresId" class ="form-control" asp-items="ViewBag.TalleresId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AkademiaV2/Views/ColaboradoresTalleres/Delete.cshtml
@model AkademiaV2.Models.ColaboradoresTalleres

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ColaboradoresTalleres</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Taller)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Taller.Descripcion)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AkademiaV2/Views/ColaboradoresTalleres/Details.cshtml
@model AkademiaV2.Models.ColaboradoresTalleres

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ColaboradoresTalleres</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Taller)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Taller.Descripcion)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AkademiaV2/Views/ColaboradoresTalleres/Edit.cshtml
@model AkademiaV2.Models.ColaboradoresTalleres

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ColaboradoresTalleres</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="TalleresId" class="control-label"></label>
                <select asp-for="TalleresId" class="form-control" asp-items="ViewBag.TalleresId"></select>
                <span asp-validation-for="TalleresId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AkademiaV2/Views/ColaboradoresTalleres/Index.cshtml
@model IEnumerable<AkademiaV2.Models.ColaboradoresTalleres>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Taller)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Taller.Descripcion)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

AkademiaV2/Views/ColaboradoresTalleres/ShowTaller_Colaboradores.cshtml
@model AkademiaV2.Models.ViewModels.Colab_Taller_AsistentesVM


<div class="row">
    <div class="col-md-4">

        <form asp-controller="ColaboradoresTalleres" asp-action="CreateTaller_Colaboradores">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Taller" class="control-label"></label>

                <select class="form-control" asp-for="TallerId">
                    <option value="@Model.Taller.Id">@Model.Taller.Nombre</option>
                </select>

            </div>
            <div class="form-group">
                <label asp-for="Escoger_Facilitadores" class="control-label"></label>

                <label>Seleccionar todos</label>
                <input class="lobilist-check" type="checkbox" id="select_all" />
                @foreach (Colaboradores facilitador in Model.Escoger_Facilitadores)
                {
                    <label>@facilitador.Nombre @facilitador.Apellidos</label>
                    <div class="custom-control custom-checkbox">
                      
                        <input class="custom-control" type="checkbox" name="facilitadores_id" id="@facilitador.Id" value="@facilitador.Id" />
                    </div>
                     

                    @*<div class="custom-file">
                        <input type="file" class="custom-file-input" id="validatedCustomFile" required>
                        <label class="custom-file-label" for="validatedCustomFile">Choose file...</label>
                        <div class="invalid-feedback">Example invalid custom file feedback</div>
                    </div>*@


                }

                <script>
                    var select_all = document.getElementById("select_all"); //select all checkbox
                    var checkboxes = document.getElementsByClassName("custom-control"); //checkbox items

                    //select all checkboxes
                    select_all.addEventListener("change", function (e) {
                        for (i = 0; i < checkboxes.length; i++) {
                            checkboxes[i].checked = select_all.checked;
                        }
                    });


                    for (var i = 0; i < checkboxes.length; i++) {
                        checkboxes[i].addEventListener('change', function (e) { //".checkbox" change
                            //uncheck "select all", if one of the listed checkbox item is unchecked
                            if (this.checked == false) {
                                select_all.checked = false;
                            }
                            //check "select all" if all checkbox items are checked
                            if (document.querySelectorAll('.checkbox:checked').length == checkboxes.length) {
                                select_all.checked = true;
                            }
                        });
                    }
                </script>

            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>