AkademiaV2/Models/Akademia.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AkademiaV2.Models
{
    public class Akademia
    {
        [Required]
        public int Id { get; set; }
        [Required(ErrorMessage = "Introduzca la Edición Actual de su Delegación")]
        public int Edicion { get; set; }
        [Required(ErrorMessage = "Porfavor Indtroduzca Una Ciudad"), MaxLength(40)]
        [DataType(DataType.Text)]
        public string Ciudad { get; set; }
        [Required(ErrorMessage = "Por favor, Introduzca la dirección de su delegación"), MaxLength(250)]
        [DataType(DataType.Text)]
        public string Direccion { get; set; }
        public string Imagen { get; set; }
        [Required]
        public string Email { get; set; }
        public List<Colaboradores> Colaboradores { get; set; }
        public List<Alumnos> Alumnos { get; set; }
        public List<Talleres> Talleres { get; set; }
    }
}

AkademiaV2/Controllers/AlumnosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AkademiaV2.Data;
using AkademiaV2.Models;
using AkademiaV2.Services;
using Microsoft.AspNetCore.Authorization;
using AkademiaV2.Models.ViewModels;

namespace AkademiaV2.Controllers
{
    public class AlumnosController : Controller
    {
        private readonly IAlumnos _alumnosServices;
        private readonly IColaboradores _colaboradoresServices;
        private readonly IAkademia _akademiaServices;

        public AlumnosController(IAlumnos alumnosServices, IColaboradores colaboradoresServices,IAkademia akademiaServices)
        {
            _alumnosServices = alumnosServices;
            _colaboradoresServices = colaboradoresServices;
            _akademiaServices = akademiaServices;
        }

        // GET: Alumnos
        public async Task<IActionResult> Index()
        {
            return View(await _alumnosServices.GetAlumnos());
        }

        // GET: Alumnos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alumnos = await _alumnosServices.GetAlumnoByIdAsync(id);
               
            if (alumnos == null)
            {
                return NotFound();
            }

            return View(alumnos);
        }


        public async Task<IActionResult> Profile(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alumnos = await _alumnosServices.GetAlumnoByIdAsync(id);

            if (alumnos == null)
            {
                return NotFound();
            }

            return View(alumnos);
        }

        // GET: Alumnos/Create
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Create()
        {

            AlumnoColaborador alumnoColaborador = new AlumnoColaborador
            {
                Colaboradores = await _colaboradoresServices.GetColaboradoresAsync(),

            };
            return View(alumnoColaborador);
        }
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> MostrarColaborador()
        {

            return View(await _alumnosServices.GetAlumnos());
        }

        // POST: Alumnos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
       
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> EleccionColaborador(AlumnoColaborador alumnoColaborador)
        {
            int id = alumnoColaborador.AlumnoColaboradores.Alumnos.Colaborador.Id;
            Colaboradores colaboradores = await _colaboradoresServices.GetColaboradorByIdAsync(id);
          
            Akademia akademia = await _akademiaServices.GetAkademiaByIdAsync(1);

            Alumnos alumno = new Alumnos
            {
                Nombre = alumnoColaborador.AlumnoColaboradores.Alumnos.Nombre,
                Apellidos = alumnoColaborador.AlumnoColaboradores.Alumnos.Apellidos,
                CartaMotivacional = alumnoColaborador.AlumnoColaboradores.Alumnos.CartaMotivacional,
                AkademiaId = akademia.Id,
                Akademia = akademia,
                 Colaborador = colaboradores,
                 ColaboradorId = colaboradores.Id,
                    Comentarios =alumnoColaborador.AlumnoColaboradores.Alumnos.Comentarios,
                    Edicion = alumnoColaborador.AlumnoColaboradores.Alumnos.Edicion,
                    Email = alumnoColaborador.AlumnoColaboradores.Alumnos.Email,
                    Entrevista = alumnoColaborador.AlumnoColaboradores.Alumnos.Entrevista,
                    FechaNacimiento = alumnoColaborador.AlumnoColaboradores.Alumnos.FechaNacimiento,                 
                    Imagen = alumnoColaborador.AlumnoColaboradores.Alumnos.Imagen,
                    Telefono =alumnoColaborador.AlumnoColaboradores.Alumnos.Telefono,
                    
                };
               
                 return View(alumno);
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmarAlumno(Alumnos alumnos)
        {
            await _alumnosServices.CreateAlumnoAsync(alumnos);
           
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Create(Alumnos alumnos)
        {
            if (ModelState.IsValid)
            {
               
                await _alumnosServices.CreateAlumnoAsync(alumnos);
                return RedirectToAction(nameof(Index));

               
            }
            return View(alumnos);
        }

        // GET: Alumnos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alumnos = await _alumnosServices.GetAlumnoByIdAsync(id);
            if (alumnos == null)
            {
                return NotFound();
            }
            return View(alumnos);
        }

        // POST: Alumnos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellidos,Imagen,Email,Telefono,CartaMotivacional,FechaNacimiento,Comentarios,Edicion")] Alumnos alumnos)
        {
            if (id != alumnos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _alumnosServices.UpdateAlumnoAsync(alumnos);
                  
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_alumnosServices.AlumnoExist(alumnos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(alumnos);
        }

        // GET: Alumnos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alumnos = await _alumnosServices.GetAlumnoByIdAsync(id);
               
            if (alumnos == null)
            {
                return NotFound();
            }

            return View(alumnos);
        }

        // POST: Alumnos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var alumnos = await _alumnosServices.GetAlumnoByIdAsync(id);
            await _alumnosServices.DeleteAlumnoAsync(alumnos);
          
            return RedirectToAction(nameof(Index));
        }
    }
}

AkademiaV2/Controllers/ColaboradoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AkademiaV2.Data;
using AkademiaV2.Models;
using AkademiaV2.Services;

namespace AkademiaV2.Controllers
{
    public class ColaboradoresController : Controller
    {
        private readonly IColaboradores _colaboradoresServices;
        private readonly IAkademia _akademiaServices;
        private readonly ITalleres _talleresServices;
        private readonly IAlumnos _alumnosSerices;
        private readonly ISesiones _sesionesServices;


        public ColaboradoresController(IColaboradores colaboradoresServices, IAkademia akademiaServices,ITalleres talleresServices, IAlumnos alumnosServices,ISesiones sesionesServices)
        {
            _colaboradoresServices = colaboradoresServices;
            _akademiaServices = akademiaServices;
            _talleresServices = talleresServices;
            _alumnosSerices = alumnosServices;
            _sesionesServices = sesionesServices;
        }

        // GET: Colaboradores
        public async Task<IActionResult> Index()
        {
            return View(await _colaboradoresServices.GetColaboradoresAsync());
        }

        public async Task<IActionResult> Facilitadores()
        {
            return View(await _colaboradoresServices.GetColaboradoresAsync());
        }

        public async Task<IActionResult> Profile(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var colaborador = await _colaboradoresServices.GetColaboradorByIdAsync(id);
            Akademia akademia = await _akademiaServices.GetAkademiaByIdAsync(1);
            colaborador.Sesiones = await _sesionesServices.GetSesionesByIdColaborador(id);
            colaborador.Akademia = akademia;

            if (colaborador == null)
            {
                return NotFound();
            }

            return View(colaborador);
        }

        // GET: Colaboradores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var colaborador = await _colaboradoresServices.GetColaboradorByIdAsync(id);
          
          
            if (colaborador== null)
            {
                return NotFound();
            }

            return View(colaborador);
        }

        // GET: Colaboradores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Colaboradores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellidos,Imagen,Email,Telefono,CartaMotivacional,FechaNacimiento,Comentarios,Edicion,TipoColaborador")] Colaboradores colaboradores)
        {
            if (ModelState.IsValid)
            {
                await _colaboradoresServices.CreateColaboradorAsync(colaboradores);
                return RedirectToAction(nameof(Index));
            }
            return View(colaboradores);
        }

        // GET: Colaboradores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var colaboradores = await _colaboradoresServices.GetColaboradorByIdAsync(id);
          
            

            if (colaboradores == null)
            {
                return NotFound();
            }
            return View(colaboradores);
        }

        // POST: Colaboradores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellidos,Imagen,Email,Telefono,CartaMotivacional,FechaNacimiento,Comentarios,Edicion,TipoColaborador,CloudCarpetaPrincipal,Akademia")] Colaboradores colaboradores)
        {
            if (id != colaboradores.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Akademia akademia = await _akademiaServices.GetAkademiaByIdAsync(1);

                    colaboradores.Akademia = akademia;
                    await _colaboradoresServices.UpdateColaboradorAsync(colaboradores);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_colaboradoresServices.ColaboradorExist(colaboradores.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(colaboradores);
        }

        // GET: Colaboradores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var colaboradores = await _colaboradoresServices.GetColaboradorByIdAsync(id);
               
            if (colaboradores == null)
            {
                return NotFound();
            }

            return View(colaboradores);
        }

        // POST: Colaboradores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var colaboradores = await _colaboradoresServices.GetColaboradorByIdAsync(id);
            await _colaboradoresServices.DeleteColaboradorAsync(colaboradores);
            
            return RedirectToAction(nameof(Index));
        }
    }
}

AkademiaV2/Views/Akademias/Create.cshtml
@model AkademiaV2.Models.Akademia

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Akademia</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Edicion" class="control-label"></label>
                <input asp-for="Edicion" class="form-control" />
                <span asp-validation-for="Edicion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ciudad" class="control-label"></label>
                <input asp-for="Ciudad" class="form-control" />
                <span asp-validation-for="Ciudad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AkademiaV2/Views/Akademias/Details.cshtml
@model AkademiaV2.Models.Akademia

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Akademia</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edicion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edicion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ciudad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ciudad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AkademiaV2/Views/Akademias/Index.cshtml
@model AkademiaV2.Models.ViewModels.AkademiaVM

@foreach (Akademia item in Model.Akademias)
                        {
    <header class="white pt-3 relative shadow">
        <div class="container-fluid">
            <div class="row p-t-b-10 ">
                <div class="col">
                    <div class="pb-3">

                        <div class="image mr-3  float-left">
                            <img class="user_avatar no-b no-p" src="@item.Imagen" alt="@item.Ciudad">
                        </div>
                        <div>
                            <h6 class="p-t-10">  @item.Ciudad</h6>
                            @item.Email
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <ul class="nav nav-material responsive-tab" id="v-pills-tab" role="tablist">
                    <li>
                        <a class="nav-link active" id="v-pills-tab1-tab" data-toggle="pill" href="#v-pills-tab1" role="tab" aria-controls="v-pills-tab1">
                            <i class="icon icon-home2"></i>Home
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" id="v-pills-payments-tab" data-toggle="pill" href="#v-pills-payments" role="tab" aria-controls="v-pills-payments" aria-selected="false"><i class="icon icon-university"></i>Talleres</a>
                    </li>

                    <li>
                        <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false"><i class="icon icon-cog"></i>Editar Perfil</a>
                    </li>
                </ul>
            </div>

        </div>
    </header>

<div class="container-fluid animatedParent animateOnce my-3">
    <div class="animated fadeInUpShort">
        <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane fade show active" id="v-pills-tab1" role="tabpanel" aria-labelledby="v-pills-home-tab">
                <div class="row">
                    <div class="col-md-3">
                        <div class="card ">

                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><i class="icon icon-mobile text-primary"></i><strong class="s-12">Phone</strong> <span class="float-right s-12">numero appuser.</span></li>
                                <li class="list-group-item"><i class="icon icon-mail text-success"></i><strong class="s-12">Email</strong> <span class="float-right s-12">@item.Email</span></li>
                                <li class="list-group-item"><i class="icon icon-address-card-o text-warning"></i><strong class="s-12">Address</strong> <span class="float-right s-12">@item.Direccion</span></li>
                                <li class="list-group-item"><i class="icon icon-web text-danger"></i> <strong class="s-12">Website</strong> <span class="float-right s-12">akademy-systems.com</span></li>
                            </ul>
                        </div>
                      

                    </div>
                    <div class="col-md-9">

                        <div class="row">
                            <div class="col-lg-4">
                                <div class="card r-3">
                                    <div class="p-4">
                                        <div class="float-right">
                                            <span class="icon-university text-light-blue s-48"></span>
                                        </div>
                                        <div class="counter-title">Edición</div>
                                        <h5 class="sc-counter mt-3">@item.Edicion</h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="card r-3">
                                    <div class="p-4">
                                        <div class="float-right">
                                            <span class="icon-stop-watch3 s-48"></span>
                                        </div>
                                        <div class="counter-title ">Horas Formación</div>
                                        <h5 class="sc-counter mt-3">405</h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="white card">
                                    <div class="p-4">
                                        <div class="float-right">
                                            <span class="icon-orders s-48"></span>
                                        </div>
                                        <div class="counter-title">Colaboradores</div>
                                    
                                        <h5 class="sc-counter mt-3">@item.Colaboradores.Count()</h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br />
                        <div class="row">
                            <div class="col-md-6">
                                <div class="card">
                                    <div class="card-header white">
                                        <h6>Colaboradores <span class="badge badge-success r-3">@item.Colaboradores.Count()</span></h6>
                                    </div>
                                    <div class="card-body">
                                        <ul class="list-inline mt-3">
                                            @foreach (Colaboradores colaboradores in item.Colaboradores)
                                            {

                                                <li class="list-inline-item ">

                                                    <div class="avatar avatar-md mr-3 mb-2 mt-1">

                                                        <a asp-controller="Colaboradores" asp-action="Profile" asp-route-id="@colaboradores.Id"><img src="@colaboradores.Imagen" alt="@colaboradores.Nombre"></a>
                                                    </div>
                                                </li>
                                            }




                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <br />
                            <div class="col-md-6">
                                <div class="card">
                                    <div class="card-header white">
                                        <h6>Alumnos <span class="badge badge-success r-3">40+</span></h6>
                                    </div>
                                    <div class="card-body">
                                        <ul class="list-inline mt-3">
                                            @foreach (Alumnos alumnos in item.Alumnos)
                                            {

                                                <li class="list-inline-item ">

                                                    <div class="avatar avatar-md mr-3 mb-2 mt-1">

                                                        <a asp-controller="Alumnos" asp-action="Profile" asp-route-id="@alumnos.Id"><img src="@alumnos.Imagen" alt="@alumnos.Nombre"></a>
                                                    </div>
                                                </li>
                                            }




                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="tab-pane fade" id="v-pills-payments" role="tabpanel" aria-labelledby="v-pills-payments-tab">

                <div class="card my-3 no-b">
                    <div class="card-body">
                        <div class="card-title">Talleres </div>
                       
                        <table id="example2" class="table table-bordered table-hover data-tables"
                               data-options='{ "paging": false; "searching":false}'>
                            <thead>
                                <tr>
                                    <th>Colaborador</th>
                                    <th>Nombre</th>
                                    <th>Karrusel</th>
                                    <th>Fecha</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (Talleres talleres in item.Talleres)
                                {
                                <tr>
                                    <td>
                                        <div class="avatar avatar-md mr-3 mb-2 mt-1">
                                            @foreach (ColaboradoresTalleres facilitadores in Model.Facilitadores.Where(o => o.TalleresId == talleres.Id))
                                            {
                                                <a asp-controller="Colaboradores" asp-action="Profile" asp-route-id="@facilitadores.Colaboradores.Id"><img src="@facilitadores.Colaboradores.Imagen" alt="@facilitadores.Colaboradores.Nombre"></a>

                                                

                                            }
                                        </div>
                                    </td>
                                    <td>@talleres.Nombre</td>
                                    <td><a href="@talleres.Karrusel"><i class="icon-document-certificate"></i></a></td>
                                    <td>@talleres.FechaTaller.ToShortDateString()</td>
                                    @if (talleres.FechaTaller < DateTime.Now)
                                    {

                                        <td> <div class="d-none d-lg-block"><span class="icon icon-circle s-12  mr-2 text-success"></span> Realizado</div></td>
                                    }
                                    else
                                    {
                                        <td> <div class="d-none d-lg-block"><span class="icon icon-circle s-12  mr-2 text-warning"></span> Pendiente</div></td>
                                    }

                                </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Colaborador</th>
                                    <th>Nombre</th>
                                    <th>Karrusel</th>
                                    <th>Fecha</th>
                                    <th>Status</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>

            </div>

            <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
                <form asp-action="Edit" class="form-horizontal">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="@item.Id" />
                    <div class="form-group">
                        <label asp-for="@item.Edicion" class="control-label"></label>
                        <input asp-for="@item.Edicion" class="form-control" />
                        <span asp-validation-for="@item.Edicion" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@item.Ciudad" class="control-label"></label>
                        <input asp-for="@item.Ciudad" class="form-control" />
                        <span asp-validation-for="@item.Ciudad" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@item.Direccion" class="control-label"></label>
                        <input asp-for="@item.Direccion" class="form-control" />
                        <span asp-validation-for="@item.Direccion" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@item.Imagen" class="control-label"></label>
                        <input asp-for="@item.Imagen" class="form-control" />
                        <span asp-validation-for="@item.Imagen" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@item.Email" class="control-label"></label>
                        <input asp-for="@item.Email" class="form-control" />
                        <span asp-validation-for="@item.Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                  
                </form>
            </div>
        </div>
    </div>
</div>
                        }