AkademiaV2/Models/Talleres.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AkademiaV2.Models
{
    public class Talleres
    {
        public int Id { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Introduzca el nombre del Taller")]
        public string Nombre { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Introduzca la Descripción del Taller")]
        public string Descripcion { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime FechaTaller { get; set; }
        [Display(Name = "Cloud link: Media")]
        public string Imagen { get; set; }
        [Display(Name = "Cloud link: Karrusel")]
        public string Karrusel { get; set; }
        [Required(ErrorMessage = "Introduzca la Edición Actual de su Delegación")]
        public int Edicion { get; set; }
        public string Evaluaciones { get; set; }
        [Display(Name = "Cloud Link: Carpeta Principal")]
        public string CarpetaPrincipal { get; set; }
        public List<ColaboradoresTalleres> ColaboradoresTalleres { get; set; }
        public List<AlumnosTalleres> AlumnosTalleres { get; set; }
        public Akademia Akademia { get; set; }
    }
}

AkademiaV2/Controllers/AlumnosTalleresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AkademiaV2.Data;
using AkademiaV2.Models;
using AkademiaV2.Services;
using Microsoft.AspNetCore.Authorization;
using AkademiaV2.Models.ViewModels;

namespace AkademiaV2.Controllers
{
    public class AlumnosTalleresController : Controller
    {
        private readonly IAlumnos _alumnosServices;
        private readonly ITalleres _talleresServices;
        private readonly IAlumnosTalleres _alumnosTalleresServices;
        private readonly IColaboradoresTalleres _colaboradoresTalleresServices;


        public AlumnosTalleresController(ITalleres talleresServices, IAlumnos alumnosServices,IAlumnosTalleres alumnosTalleres, IColaboradoresTalleres colaboradoresTalleresServices)
        {
            _alumnosServices = alumnosServices;
            _talleresServices = talleresServices;
            _alumnosTalleresServices = alumnosTalleres;
            _colaboradoresTalleresServices = colaboradoresTalleresServices;
        }


        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> ShowTaller_Alumnos(int? id)
        {

            Alumnos_en_TallerVM alumnos_en_Taller = new Alumnos_en_TallerVM
            {
              Taller= await _talleresServices.GetTallerByIdAsync(id),
              Escoger_Alumnos= await _alumnosServices.GetAlumnos(),
              

            };
            return View(alumnos_en_Taller);
        }

        // GET: AlumnosTalleres/Create
        //Creo registros con el mismo id taller y varios id alumnos a ese mismo taller.Se crean x id_alumnostaller
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> CreateTaller_Alumnos(Alumnos_en_TallerVM alumnos_En_TallerVM, int[] alumnos_id)
        {
            int Tallerid = alumnos_En_TallerVM.TallerId;
            
            foreach (int i in alumnos_id)
            {

            AlumnosTalleres alumnosTalleres = new AlumnosTalleres
            {
                Alumnos = await _alumnosServices.GetAlumnoByIdAsync(i),
                Taller = await _talleresServices.GetTallerByIdAsync(Tallerid),
            };
           
            if (ModelState.IsValid)
            {
                await _alumnosTalleresServices.CreateAlumnosTalleres(alumnosTalleres);
               
            }
            }

            return RedirectToAction("Index","Talleres");
        }

        //Muestra los alumnos para escoger cuales van a ese taller por su id.
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> ShowAlumnos_in_Taller(int? id)
        {
            var myAlumnoTallerObject = await _alumnosTalleresServices.GetTallerAlumnosByTallerId(id);

            List<Alumnos> alumnos_entaller = new List<Alumnos>();
            foreach (AlumnosTalleres alumnosTalleres in myAlumnoTallerObject)
            {
                alumnos_entaller.Add(alumnosTalleres.Alumnos);
            }
            Alumnos_en_TallerVM Showalumnos_en_Taller = new Alumnos_en_TallerVM
            {
                Taller = await _talleresServices.GetTallerByIdAsync(id),
                Escoger_Alumnos = alumnos_entaller,
            };
            return View(Showalumnos_en_Taller);
        }
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> ShowInfo_in_TallerAlumnos(int? id)
        {
            var myAlumnoTallerObject = await _alumnosTalleresServices.GetTallerAlumnosByTallerId(id);

            List<Alumnos> alumnos_entaller = new List<Alumnos>();
            foreach (AlumnosTalleres alumnosTalleres in myAlumnoTallerObject)
            {
                alumnos_entaller.Add(alumnosTalleres.Alumnos);
            }
            Alumnos_en_TallerVM Showalumnos_en_Taller = new Alumnos_en_TallerVM
            {
                Taller = await _talleresServices.GetTallerByIdAsync(id),
                Escoger_Alumnos = alumnos_entaller,
                Facilitadores= await _colaboradoresTalleresServices.GetColaboradoresTalleresByTallerId(id),
            };
            return View(Showalumnos_en_Taller);
        }


        //public async Task<IActionResult> ShowTaller_Alumnos(int? id)
        //{
        //    AlumnosTalleres alumnosTalleres = new AlumnosTalleres
        //    {
        //        //Alumnos = await _alumnosServices.GetAlumnos(),
        //        Taller = await _talleresServices.GetTallerByIdAsync(id),
        //    };

        //    return View(alumnosTalleres);
        //}



        // POST: AlumnosTalleres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id")] AlumnosTalleres alumnosTalleres)
        {
            if (ModelState.IsValid)
            {
                await _alumnosTalleresServices.CreateAlumnosTalleres(alumnosTalleres);
                return RedirectToAction(nameof(Index));
            }
            return View(alumnosTalleres);
        }

        public async Task<IActionResult> Index()
        {
            return View(await _alumnosTalleresServices.GetAlumnosTalleres());
        }

        // GET: AlumnosTalleres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alumnosTalleres = await _alumnosTalleresServices.GetAlumnosTalleresByIdAsync(id);

            if (alumnosTalleres == null)
            {
                return NotFound();
            }

            return View(alumnosTalleres);
        }

        // GET: AlumnosTalleres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alumnosTalleres = await _alumnosTalleresServices.GetAlumnosTalleresByIdAsync(id);
            if (alumnosTalleres == null)
            {
                return NotFound();
            }
            return View(alumnosTalleres);
        }

        // POST: AlumnosTalleres/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id")] AlumnosTalleres alumnosTalleres)
        {
            if (id != alumnosTalleres.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    await _alumnosTalleresServices.UpdateAlumnosTalleresAsync(alumnosTalleres);
                }
                catch (DbUpdateConcurrencyException)
                {
                    
                    if (!_alumnosTalleresServices.AlumnosTalleresExists(alumnosTalleres.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(alumnosTalleres);
        }

        // GET: AlumnosTalleres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alumnosTalleres = await _alumnosTalleresServices.GetAlumnosTalleresByIdAsync(id);
            if (alumnosTalleres == null)
            {
                return NotFound();
            }

            return View(alumnosTalleres);
        }

        // POST: AlumnosTalleres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var alumnosTalleres = await _alumnosTalleresServices.GetAlumnosTalleresByIdAsync(id);
            await _alumnosTalleresServices.DeleteAlumnosTalleresAsync(alumnosTalleres);
            return RedirectToAction(nameof(Index));
        }

    }
}

AkademiaV2/Controllers/ColaboradoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AkademiaV2.Data;
using AkademiaV2.Models;
using AkademiaV2.Services;

namespace AkademiaV2.Controllers
{
    public class ColaboradoresController : Controller
    {
        private readonly IColaboradores _colaboradoresServices;
        private readonly IAkademia _akademiaServices;
        private readonly ITalleres _talleresServices;
        private readonly IAlumnos _alumnosSerices;
        private readonly ISesiones _sesionesServices;


        public ColaboradoresController(IColaboradores colaboradoresServices, IAkademia akademiaServices,ITalleres talleresServices, IAlumnos alumnosServices,ISesiones sesionesServices)
        {
            _colaboradoresServices = colaboradoresServices;
            _akademiaServices = akademiaServices;
            _talleresServices = talleresServices;
            _alumnosSerices = alumnosServices;
            _sesionesServices = sesionesServices;
        }

        // GET: Colaboradores
        public async Task<IActionResult> Index()
        {
            return View(await _colaboradoresServices.GetColaboradoresAsync());
        }

        public async Task<IActionResult> Facilitadores()
        {
            return View(await _colaboradoresServices.GetColaboradoresAsync());
        }

        public async Task<IActionResult> Profile(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var colaborador = await _colaboradoresServices.GetColaboradorByIdAsync(id);
            Akademia akademia = await _akademiaServices.GetAkademiaByIdAsync(1);
            colaborador.Sesiones = await _sesionesServices.GetSesionesByIdColaborador(id);
            colaborador.Akademia = akademia;

            if (colaborador == null)
            {
                return NotFound();
            }

            return View(colaborador);
        }

        // GET: Colaboradores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var colaborador = await _colaboradoresServices.GetColaboradorByIdAsync(id);
          
          
            if (colaborador== null)
            {
                return NotFound();
            }

            return View(colaborador);
        }

        // GET: Colaboradores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Colaboradores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellidos,Imagen,Email,Telefono,CartaMotivacional,FechaNacimiento,Comentarios,Edicion,TipoColaborador")] Colaboradores colaboradores)
        {
            if (ModelState.IsValid)
            {
                await _colaboradoresServices.CreateColaboradorAsync(colaboradores);
                return RedirectToAction(nameof(Index));
            }
            return View(colaboradores);
        }

        // GET: Colaboradores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var colaboradores = await _colaboradoresServices.GetColaboradorByIdAsync(id);
          
            

            if (colaboradores == null)
            {
                return NotFound();
            }
            return View(colaboradores);
        }

        // POST: Colaboradores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellidos,Imagen,Email,Telefono,CartaMotivacional,FechaNacimiento,Comentarios,Edicion,TipoColaborador,CloudCarpetaPrincipal,Akademia")] Colaboradores colaboradores)
        {
            if (id != colaboradores.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Akademia akademia = await _akademiaServices.GetAkademiaByIdAsync(1);

                    colaboradores.Akademia = akademia;
                    await _colaboradoresServices.UpdateColaboradorAsync(colaboradores);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_colaboradoresServices.ColaboradorExist(colaboradores.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(colaboradores);
        }

        // GET: Colaboradores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var colaboradores = await _colaboradoresServices.GetColaboradorByIdAsync(id);
               
            if (colaboradores == null)
            {
                return NotFound();
            }

            return View(colaboradores);
        }

        // POST: Colaboradores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var colaboradores = await _colaboradoresServices.GetColaboradorByIdAsync(id);
            await _colaboradoresServices.DeleteColaboradorAsync(colaboradores);
            
            return RedirectToAction(nameof(Index));
        }
    }
}

AkademiaV2/Views/Talleres/Index.cshtml
@model List<AkademiaV2.Models.Talleres>

@{
    ViewData["Title"] = "Index";
}

<div class="container-fluid animatedParent animateOnce">
    <div class="tab-content my-3" id="v-pills-tabContent">
        <div class="tab-pane animated fadeInUpShort show active" id="v-pills-all" role="tabpanel" aria-labelledby="v-pills-all-tab">
            <div class="row my-3">
                <div class="col-md-12">
                    <div class="card r-0 shadow">
                        <div class="table-responsive">
                            <form>
                                <table class="table table-striped table-hover r-0">
                                    <thead>
                                        <tr class="no-b">
                                            <th style="width: 30px">
                                                <div class="custom-control custom-checkbox">
                                                    <input type="checkbox" id="checkedAll" class="custom-control-input"><label class="custom-control-label" for="checkedAll"></label>
                                                </div>
                                            </th>
                                            <th>Taller</th>

                                            <th> <div class="d-none d-lg-block">Edición</div></th>
                                            <th> <div class="d-none d-lg-block">Asistentes</div></th>
                                            <th> <div class="d-none d-lg-block">Facilitador</div></th>
                                            <th> <div class="d-none d-lg-block">STATUS</div></th>
                                            <th> <div class="d-none d-lg-block">Bloque</div></th>
                                            <th></th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (Talleres talleres in Model  )
                                        {

                                        <tr>
                                            <td>
                                                <div class="custom-control custom-checkbox">
                                                    <input type="checkbox" class="custom-control-input checkSingle"
                                                           id="@talleres.Id" required><label class="custom-control-label" for="@talleres.Id"></label>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="d-flex">
                                                    <div class="avatar avatar-md mr-3 mb-2 mt-1">
                                                        @*<span class="avatar-letter avatar-letter-d  avatar-md circle"></span>*@
                                                    </div>
                                                    <div>
                                                        <div>
                                                            <strong>@talleres.Nombre</strong>
                                                        </div>
                                                        <small> @talleres.FechaTaller.ToShortDateString()</small>
                                                    </div>
                                                </div>
                                            </td>

                                            <td> <div class="d-none d-lg-block">@talleres.Edicion</div></td>
                                            <td> <div class="d-none d-lg-block"></div></td>

                                            <td> <div class="d-none d-lg-block"></div></td>
                                            @if (talleres.FechaTaller < DateTime.Now)
                                            {

                                                <td> <div class="d-none d-lg-block"><span class="icon icon-circle s-12  mr-2 text-success"></span> Realizado</div></td>
                                            }
                                            else
                                            {
                                                <td> <div class="d-none d-lg-block"><span class="icon icon-circle s-12  mr-2 text-warning"></span> Pendiente</div></td>
                                            }

                                            <td> <div class="d-none d-lg-block"><span class="r-3 badge badge-success ">Administrator</span></div></td>
                                            <td>
                                                <a asp-controller="AlumnosTalleres" asp-action="ShowAlumnos_in_Taller" asp-route-id="@talleres.Id"><i class="icon-eye mr-3"></i></a>
                                              <td>

                                                <a asp-controller="AlumnosTalleres" asp-action="ShowTaller_Alumnos" asp-route-id="@talleres.Id"><i class="icon-user"></i></a>
                                              </td>  
                                              <td>
                                                <a asp-controller="AlumnosTalleres" asp-action="ShowInfo_in_TallerAlumnos" asp-route-id="@talleres.Id"><i class="icon-user"></i></a>

                                              </td>            

                                            </td>
                                        </tr>
                                        }

                                    </tbody>
                                </table>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>

            <nav class="my-3" aria-label="Page navigation">
                <ul class="pagination">
                    <li class="page-item">
                        <a class="page-link" href="#">Previous</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">1</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">2</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">3</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>

AkademiaV2/Views/Talleres/ListaTalleres.cshtml
@model AkademiaV2.Models.ViewModels.Alumno_Talleres_Facilitador_Asistencia_VM




<div class="container-fluid animatedParent animateOnce">
    <div class="tab-content my-3" id="v-pills-tabContent">
        <div class="tab-pane animated fadeInUpShort show active" id="v-pills-all" role="tabpanel" aria-labelledby="v-pills-all-tab">
            <div class="row my-3">
                <div class="col-md-12">
                    <div class="card r-0 shadow">
                        <div class="table-responsive">
                            <form>
                                <table class="table table-striped table-hover r-0">
                                    <thead>
                                        <tr class="no-b">
                                            <th style="width: 30px">
                                                <div class="custom-control custom-checkbox">
                                                    <input type="checkbox" id="checkedAll" class="custom-control-input"><label class="custom-control-label" for="checkedAll"></label>
                                                </div>
                                            </th>
                                            <th>Colaborador</th>

                                            <th> <div class="d-none d-lg-block">Facilitador/es</div></th>
                                            <th> <div class="d-none d-lg-block">Asistentes</div></th>

                                            <th> <div class="d-none d-lg-block">STATUS</div></th>
                                            <th> <div class="d-none d-lg-block">Bloque</div></th>
                                            <th> <div class="d-none d-lg-block">Ver asistentes</div></th>
                                            <th> <div class="d-none d-lg-block">Asignar asistencia</div></th>
                                            <th> <div class="d-none d-lg-block">Ver Infor</div></th> 
                                            <th> <div class="d-none d-lg-block">Asignar:Fac.</div></th>

                                            <th></th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (Talleres talleres in Model.Talleres)
                                        {

                                        <tr>
                                            <td>
                                                <div class="custom-control custom-checkbox">
                                                    <input type="checkbox" class="custom-control-input checkSingle"
                                                           id="@talleres.Id" required><label class="custom-control-label" for="@talleres.Id"></label>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="d-flex">

                                                    @foreach (ColaboradoresTalleres facilitadores in Model.Facilitadores.Where(o => o.TalleresId == talleres.Id))
                                                    {
                                                        if (facilitadores.Colaboradores.Imagen.Count() >= 2)
                                                        {

                                                    <div class="avatar avatar-sm mr-3 mb-2 mt-1">
                                                        <a asp-controller="Colaboradores" asp-action="Profile" asp-route-id="@facilitadores.Colaboradores.Id"><img src="@facilitadores.Colaboradores.Imagen" alt="@facilitadores.Colaboradores.Nombre"></a>
                                                        @*<img src="@facilitadores.Colaboradores.Imagen" alt="@facilitadores.Colaboradores.Nombre" />*@

                                                    </div>

                                                        }
                                                        else
                                                        {
                                                            <div class="avatar avatar-md mr-3 mb-2 mt-1">

                                                                <img src="@facilitadores.Colaboradores.Imagen" alt="@facilitadores.Colaboradores.Nombre" />

                                                            </div>

                                                        }
                                                    }
                                                    @*@Model.Facilitadores.Where(o => o.TalleresId == talleres.Id).Select(o => o.Colaboradores.Imagen)*@


                                                    <div>
                                                        <div>
                                                            <strong>@talleres.Nombre</strong>

                                                        </div>
                                                        <small> @talleres.FechaTaller.ToShortDateString()</small>

                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                            @foreach (ColaboradoresTalleres facilitadores in Model.Facilitadores.Where(o => o.TalleresId == talleres.Id))
                                            {
                                            <div class="d-none d-lg-block"> @facilitadores.Colaboradores.Nombre</div>
                                               
                                            }
                                            </td>


                                            <td> <div class="d-none d-lg-block">@Model.AlumnosTalleres.Where(o => o.TallerId == talleres.Id).Count().</div></td>


                                            @if (talleres.FechaTaller < DateTime.Now)
                                            {

                                                <td> <div class="d-none d-lg-block"><span class="icon icon-circle s-12  mr-2 text-success"></span> Realizado</div></td>
                                            }
                                            else
                                            {
                                                <td> <div class="d-none d-lg-block"><span class="icon icon-circle s-12  mr-2 text-warning"></span> Pendiente</div></td>
                                            }

                                            <td> <div class="d-none d-lg-block"><span class="r-3 badge badge-success ">Según f</span></div></td>
                                            <td>
                                                <a asp-controller="AlumnosTalleres" asp-action="ShowAlumnos_in_Taller" asp-route-id="@talleres.Id"><i class="icon-eye mr-3"></i></a>
                                            <td>

                                                <a asp-controller="AlumnosTalleres" asp-action="ShowTaller_Alumnos" asp-route-id="@talleres.Id"><i class="icon-users"></i></a>
                                            </td>
                                            <td>
                                                <a asp-controller="AlumnosTalleres" asp-action="ShowInfo_in_TallerAlumnos" asp-route-id="@talleres.Id"><i class="icon-profile-3"></i></a>

                                            </td>
                                            <td>
                                                <a asp-controller="ColaboradoresTalleres" asp-action="ShowTaller_Colaboradores" asp-route-id="@talleres.Id"><i class="icon-support"></i></a>
                                            </td>
                                        </tr>
                                        }

                                    </tbody>
                                </table>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<nav class="my-3" aria-label="Page navigation">
    <ul class="pagination">
        <li class="page-item">
            <a class="page-link" href="#">Previous</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="#">1</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="#">Next</a>
        </li>
    </ul>
</nav>